/* Riddle clues shown on discoverable (locked-but-reachable) Dex cards
   and by the mascot's hint ladder. One { en, fr } pair per molecule. */
export const CLUES = {
  mol_001: { en: "Every living thing drinks me — two H's holding one O.", fr: "Tout être vivant me boit — deux H tenant un O." },
  mol_002: { en: "You breathe me out; plants breathe me in.", fr: "Tu m'expires ; les plantes m'inspirent." },
  mol_003: { en: "I make food tasty and the sea salty.", fr: "Je rends la nourriture savoureuse et la mer salée." },
  mol_004: { en: "The simplest fuel — one carbon wearing four hydrogens.", fr: "Le combustible le plus simple — un carbone et quatre hydrogènes." },
  mol_005: { en: "The 'alcohol' in hand sanitizer — two carbons, one O.", fr: "L'« alcool » du gel hydroalcoolique — deux carbones, un O." },
  mol_006: { en: "A sharp-smelling cleaner — one nitrogen, three hydrogens.", fr: "Un nettoyant à l'odeur piquante — un azote, trois hydrogènes." },
  mol_007: { en: "A powerful acid hiding inside car batteries.", fr: "Un acide puissant caché dans les batteries de voiture." },
  mol_008: { en: "The sugar your body burns for energy.", fr: "Le sucre que ton corps brûle pour l'énergie." },
  mol_009: { en: "A famous pain-relief pill, first made from willow bark.", fr: "Un célèbre comprimé antidouleur, issu de l'écorce de saule." },
  mol_010: { en: "What keeps coffee drinkers wide awake.", fr: "Ce qui tient les buveurs de café bien éveillés." },
  mol_011: { en: "Two of the same atom — and every breath needs me.", fr: "Deux atomes identiques — et chaque respiration en a besoin." },
  mol_012: { en: "Like water, but with one extra oxygen — it disinfects.", fr: "Comme l'eau, mais avec un oxygène en plus — il désinfecte." },
  mol_013: { en: "Water's dangerous cousin — one carbon, one oxygen.", fr: "Le cousin dangereux de l'eau — un carbone, un oxygène." },
  mol_014: { en: "The acid in your stomach — one H, one Cl.", fr: "L'acide de ton estomac — un H, un Cl." },
  mol_015: { en: "Lye for making soap — sodium, oxygen and hydrogen.", fr: "La soude pour fabriquer du savon — sodium, oxygène et hydrogène." },
  mol_016: { en: "A perfect ring of six carbons, each with a hydrogen.", fr: "Un anneau parfait de six carbones, chacun avec un hydrogène." },
  mol_017: { en: "Mix me with water and you get vinegar.", fr: "Mélange-moi à de l'eau et tu obtiens du vinaigre." },
  mol_018: { en: "The gas in a barbecue tank — three carbons in a row.", fr: "Le gaz d'une bouteille de barbecue — trois carbones à la suite." },
  mol_019: { en: "A strong acid used for fertilizer and fireworks.", fr: "Un acide fort utilisé pour les engrais et les feux d'artifice." },
  mol_020: { en: "A volcano's choking gas — one sulfur, two oxygens.", fr: "Le gaz suffocant d'un volcan — un soufre, deux oxygènes." },
  mol_021: { en: "The lightest gas — fills balloons that float upward.", fr: "Le gaz le plus léger — il fait flotter les ballons vers le ciel." },
  mol_022: { en: "Most of every breath you take — but your body can't use it.", fr: "La plus grande partie de chaque souffle — mais ton corps ne peut pas l'utiliser." },
  mol_023: { en: "Wood alcohol — like ethanol, but with one fewer carbon.", fr: "L'alcool de bois — comme l'éthanol, mais avec un carbone en moins." },
  mol_024: { en: "Smells like rotten eggs — two hydrogens hugging a sulfur.", fr: "Sent l'œuf pourri — deux hydrogènes serrant un soufre." },
  mol_025: { en: "Strips off nail polish — a sharp-smelling solvent.", fr: "Enlève le vernis à ongles — un solvant à l'odeur piquante." },
  mol_026: { en: "The fizzing powder bakers love — meets vinegar with a hiss.", fr: "La poudre effervescente des pâtissiers — siffle au contact du vinaigre." },
  mol_027: { en: "Preserves frogs in jars — one carbon, two H's, one O.", fr: "Conserve les grenouilles dans des bocaux — un carbone, deux H, un O." },
  mol_028: { en: "Ant venom! The sting in a tiny bite.", fr: "Le venin de la fourmi ! La brûlure d'une minuscule piqûre." },
  mol_029: { en: "What ripens bananas — two carbons sharing a double bond.", fr: "Ce qui fait mûrir les bananes — deux carbones unis par une double liaison." },
  mol_030: { en: "The smallest building block of every protein in you.", fr: "La plus petite brique élémentaire de toutes tes protéines." },

  /* Myth Vault — only reachable via impossible combinations. The clues
     lean into the pop-culture origin instead of real chemistry. */
  mol_myth_001: { en: "A glowing green rock that weakens a man in a red cape — six of one element.", fr: "Une roche verte luminescente qui affaiblit un homme à la cape rouge — six d'un même élément." },
  mol_myth_002: { en: "An untameable metal alloy. Pile carbon — a lot of it.",                       fr: "Un alliage indomptable. Empile du carbone — beaucoup." },
  mol_myth_003: { en: "Hobbit chainmail — one of three different elements you've unlocked.",         fr: "Cotte de mailles de hobbit — un seul atome de chacun de trois éléments." },
  mol_myth_004: { en: "A meteor metal that drinks impacts — equal carbon and sodium clusters.",      fr: "Un métal météoritique qui boit les chocs — autant de carbone que de sodium." },
  mol_myth_005: { en: "Every element you've ever unlocked, one of each. The engineer's wish.",       fr: "Chacun des éléments débloqués, une fois. Le rêve de l'ingénieur." },
  mol_myth_006: { en: "A warp-drive crystal — pair of one alkali metal.",                            fr: "Cristal de moteur warp — paire d'un seul métal alcalin." },
  mol_myth_007: { en: "An alien crystal that eats tanks — heavy on sulfur, a little carbon.",        fr: "Cristal alien qui dévore les blindés — beaucoup de soufre, un peu de carbone." },
  mol_myth_008: { en: "The metal of a stargate — five of one element.",                              fr: "Le métal d'une Porte des Étoiles — cinq d'un même élément." },
  mol_myth_009: { en: "A glittery dust that bends mass — equal nitrogen and oxygen, five each.",     fr: "Une poussière scintillante qui courbe la masse — autant d'azote que d'oxygène, cinq chacun." },
  mol_myth_010: { en: "The 17th-century 'fire element' — five H's and a pair of O's.",               fr: "L'« élément du feu » du XVIIᵉ siècle — cinq H et deux O." },

  /* Myth Vault — wave 2 */
  mol_myth_011: { en: "What Han Solo woke up frozen in — one carbon, smothered by eight oxygens.",   fr: "Ce dans quoi Han Solo s'est réveillé congelé — un carbone, étouffé par huit oxygènes." },
  mol_myth_012: { en: "A Victorian sci-fi powder that ignores gravity — nine of the lightest atom.",  fr: "Une poudre sci-fi victorienne qui ignore la gravité — neuf du plus léger des atomes." },
  mol_myth_013: { en: "The mythic fifth element — five each of the four starter atoms.",              fr: "Le mythique cinquième élément — cinq de chacun des quatre atomes de départ." },
  mol_myth_014: { en: "Liquid gold luck — seven sodiums and a single oxygen.",                        fr: "Chance dorée en flacon — sept sodiums et un seul oxygène." },
  mol_myth_015: { en: "A spell crystallized in a green orb — seven carbons, seven sulfurs.",          fr: "Un sort cristallisé en orbe verte — sept carbones, sept soufres." },
  mol_myth_016: { en: "An addictive spice that folds space — eleven carbons, eleven hydrogens.",      fr: "Une épice addictive qui plie l'espace — onze carbones, onze hydrogènes." },
  mol_myth_017: { en: "Atlantis's lost alloy — three each of carbon, sodium, sulfur.",                fr: "Alliage perdu de l'Atlantide — trois de carbone, sodium, soufre." },
  mol_myth_018: { en: "Adamantium's weaker cousin — eleven carbons in a row.",                        fr: "Le cousin faible de l'adamantium — onze carbones d'affilée." },
  mol_myth_019: { en: "A 25th-century impenetrable metal — nine carbons, nine sodiums.",              fr: "Un métal impénétrable du XXVᵉ siècle — neuf carbones, neuf sodiums." },
  mol_myth_020: { en: "A bubbling green resurrection pool — eight hydrogens, eight oxygens.",         fr: "Bassin vert qui ressuscite — huit hydrogènes, huit oxygènes." },
};
