/* Riddle clues shown on discoverable (locked-but-reachable) Dex cards
   and by the mascot's hint ladder. One { en, fr } pair per molecule. */
export const CLUES = {
  mol_001: { en: "Every living thing drinks me — two H's holding one O.", fr: "Tout être vivant me boit — deux H tenant un O." },
  mol_002: { en: "You breathe me out; plants breathe me in.", fr: "Tu m'expires ; les plantes m'inspirent." },
  mol_003: { en: "I make food tasty and the sea salty.", fr: "Je rends la nourriture savoureuse et la mer salée." },
  mol_004: { en: "The simplest fuel — one carbon wearing four hydrogens.", fr: "Le combustible le plus simple — un carbone et quatre hydrogènes." },
  mol_005: { en: "The 'alcohol' in hand sanitizer — two carbons, one O.", fr: "L'« alcool » du gel hydroalcoolique — deux carbones, un O." },
  mol_006: { en: "A sharp-smelling cleaner — one nitrogen, three hydrogens.", fr: "Un nettoyant à l'odeur piquante — un azote, trois hydrogènes." },
  mol_007: { en: "A powerful acid hiding inside car batteries.", fr: "Un acide puissant caché dans les batteries de voiture." },
  mol_008: { en: "The sugar your body burns for energy.", fr: "Le sucre que ton corps brûle pour l'énergie." },
  mol_009: { en: "A famous pain-relief pill, first made from willow bark.", fr: "Un célèbre comprimé antidouleur, issu de l'écorce de saule." },
  mol_010: { en: "What keeps coffee drinkers wide awake.", fr: "Ce qui tient les buveurs de café bien éveillés." },
  mol_011: { en: "Two of the same atom — and every breath needs me.", fr: "Deux atomes identiques — et chaque respiration en a besoin." },
  mol_012: { en: "Like water, but with one extra oxygen — it disinfects.", fr: "Comme l'eau, mais avec un oxygène en plus — il désinfecte." },
  mol_013: { en: "Water's dangerous cousin — one carbon, one oxygen.", fr: "Le cousin dangereux de l'eau — un carbone, un oxygène." },
  mol_014: { en: "The acid in your stomach — one H, one Cl.", fr: "L'acide de ton estomac — un H, un Cl." },
  mol_015: { en: "Lye for making soap — sodium, oxygen and hydrogen.", fr: "La soude pour fabriquer du savon — sodium, oxygène et hydrogène." },
  mol_016: { en: "A perfect ring of six carbons, each with a hydrogen.", fr: "Un anneau parfait de six carbones, chacun avec un hydrogène." },
  mol_017: { en: "Mix me with water and you get vinegar.", fr: "Mélange-moi à de l'eau et tu obtiens du vinaigre." },
  mol_018: { en: "The gas in a barbecue tank — three carbons in a row.", fr: "Le gaz d'une bouteille de barbecue — trois carbones à la suite." },
  mol_019: { en: "A strong acid used for fertilizer and fireworks.", fr: "Un acide fort utilisé pour les engrais et les feux d'artifice." },
  mol_020: { en: "A volcano's choking gas — one sulfur, two oxygens.", fr: "Le gaz suffocant d'un volcan — un soufre, deux oxygènes." },
  mol_021: { en: "The lightest gas — fills balloons that float upward.", fr: "Le gaz le plus léger — il fait flotter les ballons vers le ciel." },
  mol_022: { en: "Most of every breath you take — but your body can't use it.", fr: "La plus grande partie de chaque souffle — mais ton corps ne peut pas l'utiliser." },
  mol_023: { en: "Wood alcohol — like ethanol, but with one fewer carbon.", fr: "L'alcool de bois — comme l'éthanol, mais avec un carbone en moins." },
  mol_024: { en: "Smells like rotten eggs — two hydrogens hugging a sulfur.", fr: "Sent l'œuf pourri — deux hydrogènes serrant un soufre." },
  mol_025: { en: "Strips off nail polish — a sharp-smelling solvent.", fr: "Enlève le vernis à ongles — un solvant à l'odeur piquante." },
  mol_026: { en: "The fizzing powder bakers love — meets vinegar with a hiss.", fr: "La poudre effervescente des pâtissiers — siffle au contact du vinaigre." },
  mol_027: { en: "Preserves frogs in jars — one carbon, two H's, one O.", fr: "Conserve les grenouilles dans des bocaux — un carbone, deux H, un O." },
  mol_028: { en: "Ant venom! The sting in a tiny bite.", fr: "Le venin de la fourmi ! La brûlure d'une minuscule piqûre." },
  mol_029: { en: "What ripens bananas — two carbons sharing a double bond.", fr: "Ce qui fait mûrir les bananes — deux carbones unis par une double liaison." },
  mol_030: { en: "The smallest building block of every protein in you.", fr: "La plus petite brique élémentaire de toutes tes protéines." },
};
